--CONCATENANDO INFORMAÇOES DO BANCO DE DADOS

--SEM CONCATENAÇÃO
SELECT FUN_NOME, FUN_SOBRENOME FROM FUN_FUNCIONARIOS
FUN_NOME	FUN_SOBRENOME
JOÃO	    DASILVA
MARIA	    DE SOUSA
JOSE	    ALENCAR
JOAO	    DA SILVA
MARIA	    DE SOUSA
JOSE	    ALENCAR

--COM A FUNÇÃO CONCAT
SELECT CONCAT(FUN_NOME,' ', FUN_SOBRENOME)AS NOME_COMPLETO FROM FUN_FUNCIONARIOS
NOME_COMPLETO
JOÃO DASILVA
MARIA DE SOUSA
JOSE ALENCAR
JOAO DA SILVA
MARIA DE SOUSA
JOSE ALENCAR