
--CONSULTA DE 2 TABELAS SEM JUNÇÃO
SELECT CONCAT(FUN.FUN_SOBRENOME, ',',FUN.FUN_NOME) AS NOME_FUNCIONARIO,
FUN.FUN_DATA_NASCIMENTO,
PAC_DATA_INICIAL,
PAC_DATA_FINAL,
CONVERT(TIME(0), PAC.PAC_DATA_FINAL - PAC.PAC_DATA_INICIAL) AS HORAS_TRABALHADAS
FROM FUN_FUNCIONARIOS AS FUN, PAC_PONTOS_ACESSO AS PAC WHERE FUN.FUN_ID =PAC.FUN_ID;

--CONSULTA DE 2 TABELAS COM JUNÇÃO INNER JOIN
SELECT CONCAT(FUN.FUN_SOBRENOME, ',',FUN.FUN_NOME) AS NOME_FUNCIONARIO,
FUN.FUN_DATA_NASCIMENTO,
PAC_DATA_INICIAL,
PAC_DATA_FINAL,
CONVERT(TIME(0), PAC.PAC_DATA_FINAL - PAC.PAC_DATA_INICIAL) AS HORAS_TRABALHADAS
FROM FUN_FUNCIONARIOS AS FUN INNER JOIN PAC_PONTOS_ACESSO AS PAC 
ON FUN.FUN_ID = PAC.PAC_ID;

INSERT INTO PAC_PONTOS_ACESSO (PAC_DATA_INICIAL,PAC_DATA_FINAL,FUN_ID) VALUES ('2017-02-01 07:03:00','2017-02-01 11:57:00',2);