
-- CONSULTA DE 2 TABELAS COM LEFT JOIN
SELECT CONCAT(FUN.FUN_SOBRENOME, ',',FUN.FUN_NOME) AS NOME_FUNCIONARIO,
FUN.FUN_DATA_NASCIMENTO,
PAC_DATA_INICIAL,
PAC_DATA_FINAL,
CONVERT(TIME(0), PAC.PAC_DATA_FINAL - PAC.PAC_DATA_INICIAL) AS HORAS_TRABALHADAS
FROM FUN_FUNCIONARIOS AS FUN LEFT JOIN PAC_PONTOS_ACESSO AS PAC 
ON FUN.FUN_ID = PAC.PAC_ID;