--FUNÇÃO VALOR DE TABELA EMBUTIDA

--SÃO SIMILARES A UMA VIEW(EXIBIÇÃO), POREM PERMITE
--ULTILIZAR PARAMETROS. RETOMAM UM CONJUNTO COMPLETO DE DADOS.

--Sintaxe:
CREATE FUNCTION NOME_FUNÇÃO (PARÂMETROS)
RETURNS TABLE
AS 
RETURN (DECLARAÇÃO_SELECT)

--EXEMPLO DE FUNÇÃO DE VALOR DE TABELA EMBUTIDA

CREATE FUNCTION RETORNA_ITENS(@CODIGO INT)
RETURNS TABLE
AS
RETURN(
SELECT LI.NOME_LIVRO, AU.NOME_AUTOR, ED.NOME_EDITORA 
FROM TBL_LIVROS AS LI
JOIN TBL_AUTORES AS AU
ON LI.ID_AUTOR = AU.ID_AUTOR
JOIN TBL_EDITORAS AS ED 
ON LI.ID_EDITORA = ED.ID_EDITORA
WHERE  LI.ID_LIVRO = @CODIGO)

SELECT NOME_LIVRO, NOME_AUTOR, NOME_EDITORA FROM dbo.RETORNA_ITENS (100)

--RESULTADO
-- NOME_LIVRO	                            NOME_AUTOR	NOME_EDITORA
-- LINUX COMMAND LINE AND SHELL SCRIPTING	RICHARD	     WILEY
