--Funcçoes escalares retorna apenas um unico valor especifico

--Sintax:

CREATE FUNCTION NOME_FUNCAO (@PARÂMETROS)
RETURNS TIPO_DADOS_RETORNO
AS
BEGIN
  BLOCO_DE CODIGOS
  RETURN EXPRESSÃO_RETORNO
END;
  
 --EXEMPLO DE FUNÇÃO ESCALAR

CREATE FUNCTION NOTA_MEDIA (@NOME VARCHAR(30))
RETURNS REAL
AS
BEGIN
  DECLARE @MEDIA REAL
  SELECT @MEDIA = (NOTA_1 + NOTA_2 + NOTA_3 + NOTA_4)/4  
  FROM ALUNOS
  WHERE NOME_ALUNO = @NOME 
  RETURN @MEDIA
END;

--EXECUTANDO A FUNÇÃO
SELECT dbo.NOTA_MEDIA ('ANDERSON')  

--RESULTADO

9,375  --> A FUNÇÃO ESCALAR SÓ RETORNA APENAS UM RESULTADO ESPECIFICO     
