--CTE 

WITH DADOS_PONTOS(DIFERENCA_SEGUNDOS,DATA,FUN_ID,NOME) -->CTE
AS
(
SELECT 
DATEDIFF(SECOND, PAC_DATA_INICIAL,PAC_DATA_FINAL) AS DIFERENCA_SEGUNDOS, 
CONVERT(DATE, PAC_DATA_INICIAL)AS DATA,
 FUN.FUN_ID, FUN.FUN_NOME AS NOME
 FROM PAC_PONTOS_ACESSO PAC JOIN FUN_FUNCIONARIOS FUN ON PAC.FUN_ID = FUN.FUN_ID
 )

 --SELECT CHAMANDO A CTE
SELECT DATA,FUN_ID,NOME,
(
  FORMAT(SUM(DIFERENCA_SEGUNDOS)/3600, '00')+':'+ 
  FORMAT(SUM(DIFERENCA_SEGUNDOS)%3600/60,'00')+':'+
  FORMAT(SUM(DIFERENCA_SEGUNDOS)%3600%60,'00')
) AS HORAS_TRABALHADAS
FROM DADOS_PONTOS

 GROUP BY DATA,FUN_ID, NOME