 --CRIANDO UMA FUNÇÃO 
 CREATE FUNCTION FN_CALCULA_HORA(@_SEGUNDOP_QTDES INT)
 RETURNS VARCHAR(8) AS
 BEGIN
   RETURN   FORMAT(@_SEGUNDOP_QTDES/3600, '00')+':'+ 
            FORMAT((@_SEGUNDOP_QTDES %3600)/60,'00')+':'+
            FORMAT((@_SEGUNDOP_QTDES%3600)%60,'00')
 END;


WITH DADOS_PONTOS(DIFERENCA_SEGUNDOS,DATA,FUN_ID,NOME) -->CTE
AS
(
SELECT 
DATEDIFF(SECOND, PAC_DATA_INICIAL,PAC_DATA_FINAL) AS DIFERENCA_SEGUNDOS, 
CONVERT(DATE, PAC_DATA_INICIAL)AS DATA,
 FUN.FUN_ID, FUN.FUN_NOME AS NOME
 FROM PAC_PONTOS_ACESSO PAC JOIN FUN_FUNCIONARIOS FUN ON PAC.FUN_ID = FUN.FUN_ID
 )

SELECT DATA,FUN_ID,NOME,
--CHAMANDO A FUNCÇÃO 
dbo.FN_CALCULA_HORA(SUM(DIFERENCA_SEGUNDOS)) AS HORAS_TRABALHADA
FROM DADOS_PONTOS
 GROUP BY DATA,FUN_ID, NOME


