
--INSERINDO DADOS NA TABELA PAC_PONTOS_ACESSO
ALTER PROCEDURE SPE_REGISTRAR_PONTO_ACESSO @P_FUN_ID INT, @P_DATA DATETIME
AS
BEGIN
   SET NOCOUNT ON;
   DECLARE @QTDE_PONTOS_ABERTOS INT 
   SELECT @QTDE_PONTOS_ABERTOS =  COUNT(*) FROM
   PAC_PONTOS_ACESSO WHERE FUN_ID = @P_FUN_ID 
   AND PAC_DATA_FINAL IS NULL;

   IF @QTDE_PONTOS_ABERTOS = 0
   BEGIN
      --NOVO PONTO
	  INSERT INTO PAC_PONTOS_ACESSO(PAC_DATA_INICIAL, FUN_ID) 
	  VALUES(@P_DATA,@P_FUN_ID);
   END;
   ELSE
   BEGIN
   --ATUALIZAR PONTO ABERTO
	  UPDATE PAC_PONTOS_ACESSO
	  SET PAC_DATA_FINAL = @P_DATA
	  WHERE FUN_ID = @P_FUN_ID
	  AND PAC_DATA_FINAL IS NULL;
	  
   END;
   SET NOCOUNT OFF;
END;
 
 SELECT * FROM PAC_PONTOS_ACESSO

EXEC DBO.SPE_REGISTRAR_PONTO_ACESSO 1, '2017-02-10 17:00:00'
EXEC DBO.SPE_REGISTRAR_PONTO_ACESSO 1, '2017-02-10 12:00:00'

