CREATE TABLE AVS_AVISOS_FUNCIONARIOS
(
  AVS_ID INT IDENTITY (1,1) PRIMARY KEY,
  AVS_NOME_FUNCIONARIO VARCHAR (70) NOT NULL,
  AVS_HORAS_TRABALHADAS CHAR (8) NOT NULL,
  AVS_DATA_AVISO DATE NOT NULL

);

CREATE PROCEDURE SPE_NOTIFICAR_HORAS_EXTRAS @P_DATA_REFERENCIA DATE --> CRIANDO A PROCEDURE
AS 
BEGIN
  SET NOCOUNT ON; --> ATIVA A NÃO CONTAGEN DAS LINHAS

    DECLARE CR_FUNCIONARIOS CURSOR --> CRIANDO O CURSOR

    FOR  --VINCILANDO O SELECT NO CURSOR
    SELECT DATA, NOME, HORAS_TRABALHADA FROM DBO.VW_PONTO_FUNCIONARIOS
    WHERE DATA = @P_DATA_REFERENCIA;
   
    IF OBJECT_ID(N'TEMPDB..#HORAS_EXTRAS') IS NULL --VERIFICANDO SE A TABELA TEMPORARIA HORAS_EXTRAS EXISTE NO TEMPDB
  BEGIN
     -- CRIAR TABELA TEMPORARIA
	   CREATE TABLE #HORAS_EXTRAS
	   (
	      NOME_FUNCIONARIO VARCHAR(70),
		  DATA_EVENTO DATE,
		  HORAS_TRABALHADAS CHAR(8)
	   )
  END;
   ELSE
  BEGIN
     -- LIMPAR A TABELA TEMPORARIA
	  DELETE FROM #HORAS_EXTRAS
  END;
  -- CRIAR AS VARIAVEIS QUE IRAM SER RETORNADAS PELO CURSOR
  DECLARE @DATA DATE;
  DECLARE @NOME_FUNCIONARIO VARCHAR(70);
  DECLARE @HORAS_TRABALHADA CHAR(8);
  DECLARE @TEMPO_TRABALADO INT;

  -- OBS: SEMPRE QUE USAR UM CURSOR, EXECUTE ESSES COMANDOS PARA ABRIR, FECHAR E DESALOCAR O CURSOR
   OPEN CR_FUNCIONARIOS; --> ABRIR O CURSOR
   FETCH NEXT FROM CR_FUNCIONARIOS --> COMANDO PARA APONTAR A PRIMEIRA LINHA DO CURSOR
     INTO @DATA, @NOME_FUNCIONARIO, @HORAS_TRABALHADA
	 WHILE @@FETCH_STATUS = 0
	 BEGIN
	   SET @TEMPO_TRABALADO = DATEPART(SECOND, CONVERT(TIME(0),@HORAS_TRABALHADA))+
	                          DATEPART(MINUTE, CONVERT(TIME(0),@HORAS_TRABALHADA)) * 60 +
							  DATEPART(HOUR, CONVERT(TIME(0),@HORAS_TRABALHADA)) * 3600
       IF @TEMPO_TRABALADO >8*60*60
	     BEGIN
		    INSERT INTO #HORAS_EXTRAS (NOME_FUNCIONARIO,DATA_EVENTO,HORAS_TRABALHADAS)
			       VALUES (@NOME_FUNCIONARIO,@DATA,@HORAS_TRABALHADA)
		 END;
       FETCH NEXT FROM CR_FUNCIONARIOS
     INTO @DATA, @NOME_FUNCIONARIO, @HORAS_TRABALHADA

	 END;
   CLOSE CR_FUNCIONARIOS; --> FECHAR O CURSIR
   DEALLOCATE CR_FUNCIONARIOS; --> DESALOCAR O CURSOR

   INSERT INTO AVS_AVISOS_FUNCIONARIOS (AVS_NOME_FUNCIONARIO,AVS_HORAS_TRABALHADAS, AVS_DATA_AVISO)
   SELECT NOME_FUNCIONARIO,HORAS_TRABALHADAS, DATA_EVENTO FROM #HORAS_EXTRAS

  SET NOCOUNT OFF; -->DESATIVANDO A NÃO CONTAGEN DAS LINHAS

END;


