SELECT DEP.NOME_DEPARTAMENTO AS 'NOME DO DEPARTAMENTO', 
CONCAT(FUN.FUN_NOME,' ', FUN.FUN_SOBRENOME) AS 'NOME DO FUNCIONARIO',
CONVERT(DATE, PAC.PAC_DATA_INICIAL) AS 'DIA TRABALHADO',
CONVERT(TIME(0),PAC.PAC_DATA_INICIAL) AS 'ENTRADA',
CONVERT(TIME(0),PAC.PAC_DATA_FINAL) AS 'SAIDA',
CONVERT(TIME(0),PAC.PAC_DATA_FINAL - PAC.PAC_DATA_INICIAL) AS 'HORAS TRABALHADAS',
CONCAT(FUN2.FUN_NOME,' ',FUN2.FUN_SOBRENOME) AS 'NOME DO RESPONSAVEL'
FROM FUN_FUNCIONARIOS AS FUN
LEFT JOIN PAC_PONTOS_ACESSO AS PAC
ON FUN.FUN_ID = PAC.FUN_ID
INNER JOIN DEP_DEPARTAMENTOS AS DEP
ON FUN.DEP_ID = DEP.DEP_ID
INNER JOIN FUN_FUNCIONARIOS AS FUN2
ON FUN2.FUN_ID = DEP.FUN_ID_RESPONSAVEL
 