--SELECT DE CONTAGEM SIMPLES TRAZENDO TODOS OS CAMPOS DA TABELA
SELECT * FROM FUN_FUNCIONARIOS;
--FUN_ID	FUN_NOME	FUN_SOBRENOME	FUN_DATA_NASCIMENTO	FUN_OBSERVACOES	             FUN_CPF	   DEP_ID
--1	        ANDERSON	GABRIEL	        1983-07-20	         OBSERVAÇÃO DO FUNCIONARIO	 32003705805	2
--2     	MARIA	    DE SOUSA	    1990-07-03	          NULL	                     12312312312	1
--3     	JOÃO	    ALENCAR	        1968-12-05	          NULL	                     33355544411	3

-----------------------------------------------------------------------------------------------------------------------
--SELECT COM A FUNÇÃO "COUNT" TRAZENDO A CONTAGEM DE LINHAS DA TABELA
--AMBAS CONSULTA GERAM O MESMO RESULTADO
SELECT COUNT(*) AS TOTAL_REGISTROS FROM FUN_FUNCIONARIOS;
SELECT COUNT(FUN_ID) AS TOTAL_REGISTROS FROM FUN_FUNCIONARIOS;
--TOTAL_REGISTROS
--3

--------------------------------------------------------------------------------
-- A FUNÇÃO COUNT NÃO FAZ CONTAGEM DE RESTROS NULL, VEJA O EXPLO
SELECT FUN_NOME, FUN_OBSERVACOES FROM FUN_FUNCIONARIOS WHERE FUN_OBSERVACOES IS NULL
---FUN_NOME	 FUN_OBSERVACOES
--MARIA	     NULL
--JOÃO	     NULL

SELECT COUNT(FUN_OBSERVACOES) AS TOTAL_REGISTROS FROM FUN_FUNCIONARIOS;
--Mensagem 8117, Nível 16, Estado 1, Linha 23
--O tipo de dados de operando text é inválido para o operador count.

--PARA TRAZER A CONTAGEM DOS REGISTROS, SERÁ NECESSARIO CONVERTE-LA
SELECT COUNT(CONVERT( VARCHAR, FUN_OBSERVACOES)) AS TOTAL_REGISTROS FROM FUN_FUNCIONARIOS;

----------------------------------------------------------------------------------
--FUNÇÃO MIN BUSCA O VALOR MINIMO DO DADO 

SELECT MIN(FUN_DATA_NASCIMENTO) AS ANIVERSARIO_FUNCIONARIO_VELHO FROM FUN_FUNCIONARIOS;

--FUNÇÃO MAX BUSCA O VALOR MAXIMO DO DADO

SELECT MAX(FUN_DATA_NASCIMENTO) AS ANIVERSARIO_FUNCIONARIO_NOVO FROM FUN_FUNCIONARIOS;
---------------------------------------------------------------------------------------------------
--FAZENDO UMA CONSULTA COM SUBCONSULTA 
SELECT FUN_NOME, FUN_SOBRENOME, FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS WHERE FUN_DATA_NASCIMENTO = 
( SELECT MIN(FUN_DATA_NASCIMENTO) FROM FUN_FUNCIONARIOS);
--FUN_NOME	FUN_SOBRENOME	FUN_DATA_NASCIMENTO
--JOÃO	    ALENCAR	        1968-12-05
-------------------------------------------------------------------------------------------------
SELECT FUN_NOME, FUN_SOBRENOME, FUN_DATA_NASCIMENTO FROM FUN_FUNCIONARIOS WHERE FUN_DATA_NASCIMENTO = 
( SELECT MAX(FUN_DATA_NASCIMENTO) FROM FUN_FUNCIONARIOS);
--FUN_NOME	FUN_SOBRENOME	FUN_DATA_NASCIMENTO
--TREINA	WEB	            2005-02-10

--------------------------------------------------------------------------------------------------
--


