
--FILTRANDO DADOS DE UM CAMPO TIPO DATE COM AS FUNÇOES TSQL YEAR(ANO), MONTH(MÊS) E DAY(DIA)
SELECT CONCAT(FUN_NOME, ' ',FUN_SOBRENOME) AS NOME_COMPLETO,FUN_DATA_NASCIMENTO 
FROM FUN_FUNCIONARIOS 
WHERE YEAR(FUN_DATA_NASCIMENTO) = 1983 AND MONTH(FUN_DATA_NASCIMENTO)= 07 OR MONTH(FUN_DATA_NASCIMENTO) = 12;
--NOME_COMPLETO	    FUN_DATA_NASCIMENTO
--ANDERSON GABRIEL	1983-07-20
--JOÃO ALENCAR	    1968-12-05

--FAZENDO FILTRAGEM COM A FUNÇÃO (DATEDIFF) NO CAMPO DATE E USANDO OUTRO FILTRO PARA PEGAR A DATA ATUAL COM A FUNÇÃO GETDATE
--OBS: NESSA FILTRAGEM IREMOS FILTAR FUNCIONARIOS QUE TENHAM 25 ANOS OU MAIS.  
SELECT CONCAT(FUN_NOME,' ' ,FUN_SOBRENOME) AS NOME_COMPLETO 
FROM FUN_FUNCIONARIOS 
WHERE DATEDIFF(YEAR,FUN_DATA_NASCIMENTO, GETDATE()) >= 25;
--NOME_COMPLETO	    FUN_DATA_NASCIMENTO
--ANDERSON GABRIEL	1983-07-20
--JOÃO ALENCAR	    1968-12-05
