
--NESSA CONSULTA A FILTRAGEM DAS INFORMAÇOES IRÃO DESPARAR UM ERRO
SELECT CONCAT(FUN_NOME,' ',FUN_SOBRENOME) AS NOME_COMPLETO, FUN_OBSERVACOES 
FROM FUN_FUNCIONARIOS WHERE FUN_OBSERVACOES = NULL;
--Mensagem 306, Nível 16, Estado 1, Linha 3
--Os tipos de dados text, ntext e image não podem ser comparados ou classificados, exceto ao usar o operador IS NULL ou LIKE.


SELECT CONCAT(FUN_NOME,' ',FUN_SOBRENOME) AS NOME_COMPLETO, FUN_OBSERVACOES 
FROM FUN_FUNCIONARIOS WHERE FUN_OBSERVACOES IS NULL;
--NOME_COMPLETO	   FUN_OBSERVACOES
--MARIA DE SOUSA	NULL
--JOÃO ALENCAR	    NULL


