SELECT * FROM FUN_FUNCIONARIOS
SELECT * FROM PAC_PONTOS_ACESSO



select a.PAC_DATA_INICIAL as [Data],
	b.FUN_NOME as [Nome],
	b.FUN_SOBRENOME as [Sobrenome],
	(select DATEDIFF(SECOND, PAC_DATA_INICIAL,PAC_DATA_FINAL) AS DIFERENCA_SEGUNDOS) as [Horas Trabalhadas]


from PAC_PONTOS_ACESSO as a join FUN_FUNCIONARIOS as b on a.FUN_ID = b.FUN_ID